// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"test_task/models"
)

// DeleteUsersOKCode is the HTTP code returned for type DeleteUsersOK
const DeleteUsersOKCode int = 200

/*DeleteUsersOK Результат запроса

swagger:response deleteUsersOK
*/
type DeleteUsersOK struct {
}

// NewDeleteUsersOK creates DeleteUsersOK with default headers values
func NewDeleteUsersOK() *DeleteUsersOK {

	return &DeleteUsersOK{}
}

// WriteResponse to the client
func (o *DeleteUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteUsersBadRequestCode is the HTTP code returned for type DeleteUsersBadRequest
const DeleteUsersBadRequestCode int = 400

/*DeleteUsersBadRequest Некорректный запрос

swagger:response deleteUsersBadRequest
*/
type DeleteUsersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUsersBadRequest creates DeleteUsersBadRequest with default headers values
func NewDeleteUsersBadRequest() *DeleteUsersBadRequest {

	return &DeleteUsersBadRequest{}
}

// WithPayload adds the payload to the delete users bad request response
func (o *DeleteUsersBadRequest) WithPayload(payload *models.Error) *DeleteUsersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users bad request response
func (o *DeleteUsersBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsersInternalServerErrorCode is the HTTP code returned for type DeleteUsersInternalServerError
const DeleteUsersInternalServerErrorCode int = 500

/*DeleteUsersInternalServerError Внутренняя ошибка сервера

swagger:response deleteUsersInternalServerError
*/
type DeleteUsersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUsersInternalServerError creates DeleteUsersInternalServerError with default headers values
func NewDeleteUsersInternalServerError() *DeleteUsersInternalServerError {

	return &DeleteUsersInternalServerError{}
}

// WithPayload adds the payload to the delete users internal server error response
func (o *DeleteUsersInternalServerError) WithPayload(payload *models.Error) *DeleteUsersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users internal server error response
func (o *DeleteUsersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
