// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"test_task/models"
)

// PatchUsersOKCode is the HTTP code returned for type PatchUsersOK
const PatchUsersOKCode int = 200

/*PatchUsersOK Результат запроса

swagger:response patchUsersOK
*/
type PatchUsersOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPatchUsersOK creates PatchUsersOK with default headers values
func NewPatchUsersOK() *PatchUsersOK {

	return &PatchUsersOK{}
}

// WithPayload adds the payload to the patch users o k response
func (o *PatchUsersOK) WithPayload(payload *models.User) *PatchUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users o k response
func (o *PatchUsersOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUsersBadRequestCode is the HTTP code returned for type PatchUsersBadRequest
const PatchUsersBadRequestCode int = 400

/*PatchUsersBadRequest Некорректный запрос

swagger:response patchUsersBadRequest
*/
type PatchUsersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUsersBadRequest creates PatchUsersBadRequest with default headers values
func NewPatchUsersBadRequest() *PatchUsersBadRequest {

	return &PatchUsersBadRequest{}
}

// WithPayload adds the payload to the patch users bad request response
func (o *PatchUsersBadRequest) WithPayload(payload *models.Error) *PatchUsersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users bad request response
func (o *PatchUsersBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUsersInternalServerErrorCode is the HTTP code returned for type PatchUsersInternalServerError
const PatchUsersInternalServerErrorCode int = 500

/*PatchUsersInternalServerError Внутренняя ошибка сервера

swagger:response patchUsersInternalServerError
*/
type PatchUsersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUsersInternalServerError creates PatchUsersInternalServerError with default headers values
func NewPatchUsersInternalServerError() *PatchUsersInternalServerError {

	return &PatchUsersInternalServerError{}
}

// WithPayload adds the payload to the patch users internal server error response
func (o *PatchUsersInternalServerError) WithPayload(payload *models.Error) *PatchUsersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users internal server error response
func (o *PatchUsersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
