// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "CRUD server",
    "title": "CRUD server",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/users": {
      "get": {
        "description": "Получить всех пользователей.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "operationId": "GetUsers",
        "responses": {
          "200": {
            "description": "Результат запроса",
            "schema": {
              "$ref": "#/definitions/AllUserResponse"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Добавить нового пользователя.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "description": "Данные пользователя",
            "name": "loadUser",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Результат запроса",
            "schema": {
              "$ref": "#/definitions/UserUploadResponse"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Удалить пользователя.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "description": "ID пользователя.",
            "name": "IDUSer",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UserUploadResponse"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Результат запроса"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Обновить данные пользователя по ID.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "description": "ID пользователя.",
            "name": "IDUSer",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Результат запроса",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AllUserResponse": {
      "type": "object",
      "properties": {
        "Users": {
          "description": "Список всех пользователей.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "description": "Описание ошибки.",
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "name",
        "age",
        "email"
      ],
      "properties": {
        "age": {
          "description": "Возраст",
          "type": "string",
          "x-go-custom-tag": "sql:\"age\""
        },
        "email": {
          "description": "эл. адрес",
          "type": "string",
          "x-go-custom-tag": "sql:\"email\""
        },
        "id": {
          "description": "ID пользователя в БД.",
          "type": "string",
          "x-go-custom-tag": "sql:\"id\""
        },
        "name": {
          "description": "ФИО пользователя",
          "type": "string",
          "x-go-custom-tag": "sql:\"name\""
        }
      }
    },
    "UserUploadResponse": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "description": "ID пользователя в БД.",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "CRUD server",
    "title": "CRUD server",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/users": {
      "get": {
        "description": "Получить всех пользователей.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "operationId": "GetUsers",
        "responses": {
          "200": {
            "description": "Результат запроса",
            "schema": {
              "$ref": "#/definitions/AllUserResponse"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Добавить нового пользователя.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "description": "Данные пользователя",
            "name": "loadUser",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Результат запроса",
            "schema": {
              "$ref": "#/definitions/UserUploadResponse"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Удалить пользователя.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "description": "ID пользователя.",
            "name": "IDUSer",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UserUploadResponse"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Результат запроса"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Обновить данные пользователя по ID.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "description": "ID пользователя.",
            "name": "IDUSer",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Результат запроса",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутренняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AllUserResponse": {
      "type": "object",
      "properties": {
        "Users": {
          "description": "Список всех пользователей.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "description": "Описание ошибки.",
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "name",
        "age",
        "email"
      ],
      "properties": {
        "age": {
          "description": "Возраст",
          "type": "string",
          "x-go-custom-tag": "sql:\"age\""
        },
        "email": {
          "description": "эл. адрес",
          "type": "string",
          "x-go-custom-tag": "sql:\"email\""
        },
        "id": {
          "description": "ID пользователя в БД.",
          "type": "string",
          "x-go-custom-tag": "sql:\"id\""
        },
        "name": {
          "description": "ФИО пользователя",
          "type": "string",
          "x-go-custom-tag": "sql:\"name\""
        }
      }
    },
    "UserUploadResponse": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "description": "ID пользователя в БД.",
          "type": "string"
        }
      }
    }
  }
}`))
}
